export { default as About } from './about';
export { default as Timeline } from './timeline';
export { default as GettingStarted } from './gettingstarted';
export { default as News } from './news';
export { default as Footer } from './footer';
export { default as Banner } from './banner';
export { default as Nav } from './nav';
export { default as Form } from './form';
export { default as Sidebar } from './sidebar';
